"""AI-Factory Core v2.0 - Foundation primitives for ML lifecycle management.

This module provides core abstractions for:
- Hardware-accelerated training and inference
- Async/await patterns for ML workflows
- Type-safe configuration and schemas
- Distributed orchestration primitives
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ai_factory.core.answers import (
        answer_key,
        answers_equivalent,
        candidate_agreement,
        choose_best_candidate,
        classify_prediction_failure,
        compute_step_correctness,
        detect_arithmetic_slip,
        detect_formatting_failure,
        extract_final_answer,
        resolve_calculator_tags,
        split_reasoning,
        verify_prediction,
    )
    from ai_factory.core.artifacts import (
        ArtifactLayout,
        RunEnv,
        current_git_sha,
        detect_run_env,
        ensure_latest_pointer,
        prepare_run_layout,
        read_jsonl,
        sha256_file,
        sha256_text,
        write_json,
        write_jsonl,
        write_markdown,
    )
    from ai_factory.core.async_utils import (
        AsyncContextManager,
        BatchProcessor,
        async_wrap,
        gather_with_concurrency,
        retry_with_backoff,
        run_with_timeout,
    )
    from ai_factory.core.hashing import normalize_text, stable_question_fingerprint
    from ai_factory.core.schemas import (
        Alert,
        ArchitectureSpec,
        AutoDeploymentPolicy,
        AutonomousExperimentConfig,
        BackendType,
        ChatMessage,
        ContaminationStatus,
        DatasetBuildInfo,
        DatasetFileInfo,
        DatasetManifest,
        DatasetSpec,
        DeploymentSpec,
        DeploymentTarget,
        DomainType,
        EvaluationCriterion,
        GeneratorMetadata,
        HardwareProfile,
        IterationStrategy,
        MathRecord,
        MathRecordV2,
        MetricPoint,
        MetricSpec,
        ModelArtifact,
        ModelCapability,
        ModelLineage,
        MonitoringConfig,
        OptimizationConfig,
        OptimizationObjective,
        OptimizerType,
        PackagedMathRecord,
        PackagedMathRecordV2,
        PerformanceProfile,
        QuantizationType,
        ResourceBudget,
        ResourceProfile,
        ResourceSpec,
        RunManifest,
        ScalingConfig,
        SearchSpaceSpec,
        SourceLineage,
        StepCheck,
        TitanConfig,
        TrainingJob,
        UniversalModelSpec,
    )


_EXPORT_MODULES = {
    "Alert": "ai_factory.core.schemas",
    "ArchitectureSpec": "ai_factory.core.schemas",
    "ArtifactLayout": "ai_factory.core.artifacts",
    "AsyncContextManager": "ai_factory.core.async_utils",
    "AutoDeploymentPolicy": "ai_factory.core.schemas",
    "AutonomousExperimentConfig": "ai_factory.core.schemas",
    "BackendType": "ai_factory.core.schemas",
    "BatchProcessor": "ai_factory.core.async_utils",
    "ChatMessage": "ai_factory.core.schemas",
    "ContaminationStatus": "ai_factory.core.schemas",
    "DatasetBuildInfo": "ai_factory.core.schemas",
    "DatasetFileInfo": "ai_factory.core.schemas",
    "DatasetManifest": "ai_factory.core.schemas",
    "DatasetSpec": "ai_factory.core.schemas",
    "DeploymentSpec": "ai_factory.core.schemas",
    "DeploymentTarget": "ai_factory.core.schemas",
    "DomainType": "ai_factory.core.schemas",
    "EvaluationCriterion": "ai_factory.core.schemas",
    "GeneratorMetadata": "ai_factory.core.schemas",
    "HardwareProfile": "ai_factory.core.schemas",
    "IterationStrategy": "ai_factory.core.schemas",
    "MathRecord": "ai_factory.core.schemas",
    "MathRecordV2": "ai_factory.core.schemas",
    "MetricPoint": "ai_factory.core.schemas",
    "MetricSpec": "ai_factory.core.schemas",
    "ModelArtifact": "ai_factory.core.schemas",
    "ModelCapability": "ai_factory.core.schemas",
    "ModelLineage": "ai_factory.core.schemas",
    "MonitoringConfig": "ai_factory.core.schemas",
    "OptimizationConfig": "ai_factory.core.schemas",
    "OptimizationObjective": "ai_factory.core.schemas",
    "OptimizerType": "ai_factory.core.schemas",
    "PackagedMathRecord": "ai_factory.core.schemas",
    "PackagedMathRecordV2": "ai_factory.core.schemas",
    "PerformanceProfile": "ai_factory.core.schemas",
    "QuantizationType": "ai_factory.core.schemas",
    "ResourceBudget": "ai_factory.core.schemas",
    "ResourceProfile": "ai_factory.core.schemas",
    "ResourceSpec": "ai_factory.core.schemas",
    "RunEnv": "ai_factory.core.artifacts",
    "RunManifest": "ai_factory.core.schemas",
    "ScalingConfig": "ai_factory.core.schemas",
    "SearchSpaceSpec": "ai_factory.core.schemas",
    "SourceLineage": "ai_factory.core.schemas",
    "StepCheck": "ai_factory.core.schemas",
    "TitanConfig": "ai_factory.core.schemas",
    "TrainingJob": "ai_factory.core.schemas",
    "UniversalModelSpec": "ai_factory.core.schemas",
    "answer_key": "ai_factory.core.answers",
    "answers_equivalent": "ai_factory.core.answers",
    "async_wrap": "ai_factory.core.async_utils",
    "candidate_agreement": "ai_factory.core.answers",
    "choose_best_candidate": "ai_factory.core.answers",
    "classify_prediction_failure": "ai_factory.core.answers",
    "compute_step_correctness": "ai_factory.core.answers",
    "current_git_sha": "ai_factory.core.artifacts",
    "detect_arithmetic_slip": "ai_factory.core.answers",
    "detect_formatting_failure": "ai_factory.core.answers",
    "detect_run_env": "ai_factory.core.artifacts",
    "ensure_latest_pointer": "ai_factory.core.artifacts",
    "extract_final_answer": "ai_factory.core.answers",
    "gather_with_concurrency": "ai_factory.core.async_utils",
    "normalize_text": "ai_factory.core.hashing",
    "prepare_run_layout": "ai_factory.core.artifacts",
    "read_jsonl": "ai_factory.core.artifacts",
    "resolve_calculator_tags": "ai_factory.core.answers",
    "retry_with_backoff": "ai_factory.core.async_utils",
    "run_with_timeout": "ai_factory.core.async_utils",
    "sha256_file": "ai_factory.core.artifacts",
    "sha256_text": "ai_factory.core.artifacts",
    "split_reasoning": "ai_factory.core.answers",
    "stable_question_fingerprint": "ai_factory.core.hashing",
    "verify_prediction": "ai_factory.core.answers",
    "write_json": "ai_factory.core.artifacts",
    "write_jsonl": "ai_factory.core.artifacts",
    "write_markdown": "ai_factory.core.artifacts",
}

__all__ = [
    "Alert",
    "ArchitectureSpec",
    "ArtifactLayout",
    "AsyncContextManager",
    "AutoDeploymentPolicy",
    "AutonomousExperimentConfig",
    "BackendType",
    "BatchProcessor",
    "ChatMessage",
    "ContaminationStatus",
    "DatasetBuildInfo",
    "DatasetFileInfo",
    "DatasetManifest",
    "DatasetSpec",
    "DeploymentSpec",
    "DeploymentTarget",
    "DomainType",
    "EvaluationCriterion",
    "GeneratorMetadata",
    "HardwareProfile",
    "IterationStrategy",
    "MathRecord",
    "MathRecordV2",
    "MetricPoint",
    "MetricSpec",
    "ModelArtifact",
    "ModelCapability",
    "ModelLineage",
    "MonitoringConfig",
    "OptimizationConfig",
    "OptimizationObjective",
    "OptimizerType",
    "PackagedMathRecord",
    "PackagedMathRecordV2",
    "PerformanceProfile",
    "QuantizationType",
    "ResourceBudget",
    "ResourceProfile",
    "ResourceSpec",
    "RunEnv",
    "RunManifest",
    "ScalingConfig",
    "SearchSpaceSpec",
    "SourceLineage",
    "StepCheck",
    "TitanConfig",
    "TrainingJob",
    "UniversalModelSpec",
    "answer_key",
    "answers_equivalent",
    "async_wrap",
    "candidate_agreement",
    "choose_best_candidate",
    "classify_prediction_failure",
    "compute_step_correctness",
    "current_git_sha",
    "detect_arithmetic_slip",
    "detect_formatting_failure",
    "detect_run_env",
    "ensure_latest_pointer",
    "extract_final_answer",
    "gather_with_concurrency",
    "normalize_text",
    "prepare_run_layout",
    "read_jsonl",
    "resolve_calculator_tags",
    "retry_with_backoff",
    "run_with_timeout",
    "sha256_file",
    "sha256_text",
    "split_reasoning",
    "stable_question_fingerprint",
    "verify_prediction",
    "write_json",
    "write_jsonl",
    "write_markdown",
]


def __getattr__(name: str) -> object:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
