"use client";

import Link from "next/link";

import { formatCount, formatFixed, formatPercent } from "@/lib/formatting";
import { useLabMetadata } from "@/hooks/use-lab-metadata";
import { ROUTES } from "@/lib/routes";

import { AppShell } from "@/components/layout/app-shell";
import { MetricBadge } from "@/components/panels/metric-badge";
import { PageHeader } from "@/components/ui/page-header";
import { StatePanel } from "@/components/ui/state-panel";

export function RunsView() {
  const metadata = useLabMetadata();
  const runs = [...metadata.runs].sort((left, right) =>
    String(right.output_dir).localeCompare(String(left.output_dir)),
  );
  const latest = runs[0];

  return (
    <AppShell>
      <section className="route-stack">
        <PageHeader
          eyebrow="Experiment Runs"
          title="Artifacts, metrics, and trainable ratios"
          description="Inspect the locally discovered training runs, parameter reports, and evaluation metrics generated by the Atlas artifact registry."
          metrics={[
            { label: "Runs", value: formatCount(runs.length) },
            {
              label: "Latest trainable",
              value: formatPercent(latest?.model_report.trainable_ratio, 2),
              tone: "secondary",
            },
            {
              label: "Latest eval loss",
              value: formatFixed(latest?.metrics.eval_loss),
              tone: "accent",
            },
          ]}
          actions={
            <>
              <Link className="ghost-button small" href={ROUTES.benchmarks}>
                Benchmark library
              </Link>
              <Link className="primary-button small" href={ROUTES.solve}>
                Open solve workspace
              </Link>
            </>
          }
        />

        {metadata.loading && !runs.length ? (
          <StatePanel
            eyebrow="Loading"
            title="Run metadata is loading."
            description="Atlas is scanning local run manifests and model reports."
            tone="loading"
          />
        ) : null}

        {metadata.error && !runs.length ? (
          <StatePanel
            eyebrow="Unavailable"
            title="Run metadata could not be loaded."
            description={metadata.error}
            tone="error"
          />
        ) : null}

        {!metadata.loading && !runs.length ? (
          <StatePanel
            eyebrow="No Runs"
            title="No run artifacts have been discovered yet."
            description="Use the training dry-run or a full training profile to populate the local run registry."
          />
        ) : null}

        <div className="card-grid compact">
          {runs.map((run) => (
            <article key={run.run_id ?? run.run_name} className="panel catalog-panel">
              <div className="message-meta">
                <span>{run.profile_name ?? "profile"}</span>
                <span className="status-pill">{run.base_model}</span>
              </div>
              <h2>{run.run_name}</h2>
              <div className="badge-row">
                <MetricBadge
                  label="Trainable"
                  value={formatPercent(run.model_report.trainable_ratio, 2)}
                />
                <MetricBadge label="Eval loss" value={formatFixed(run.metrics.eval_loss)} tone="accent" />
              </div>
              <div className="preview-block subtle">
                <strong>Artifacts</strong>
                <p>{run.output_dir}</p>
              </div>
            </article>
          ))}
        </div>
      </section>
    </AppShell>
  );
}
