"""initial_schema

Revision ID: 53a4189ee058
Revises: 
Create Date: 2026-03-31 23:49:50.336438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a4189ee058'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decisions_today', sa.Integer(), nullable=False),
    sa.Column('current_target', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automl_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('search_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('hyperparams', sa.JSON(), nullable=False),
    sa.Column('eval_loss', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('training_minutes', sa.Float(), nullable=True),
    sa.Column('step_pruned', sa.Integer(), nullable=True),
    sa.Column('prune_reason', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automl_searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('search_space', sa.JSON(), nullable=False),
    sa.Column('best_loss', sa.Float(), nullable=True),
    sa.Column('best_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('gpus_json', sa.JSON(), nullable=False),
    sa.Column('cpu_utilization', sa.Float(), nullable=False),
    sa.Column('ram_used_gb', sa.Float(), nullable=False),
    sa.Column('ram_total_gb', sa.Float(), nullable=False),
    sa.Column('network_rx_mbps', sa.Float(), nullable=False),
    sa.Column('network_tx_mbps', sa.Float(), nullable=False),
    sa.Column('active_jobs', sa.JSON(), nullable=False),
    sa.Column('cost_per_hour', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('quality_score_mean', sa.Float(), nullable=False),
    sa.Column('quality_score_p10', sa.Float(), nullable=False),
    sa.Column('quality_score_p90', sa.Float(), nullable=False),
    sa.Column('size_mb', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('pipeline_config_hash', sa.String(), nullable=False),
    sa.Column('git_sha', sa.String(), nullable=False),
    sa.Column('pack_summary_json', sa.JSON(), nullable=True),
    sa.Column('samples_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineage_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineage_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_checkpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_model', sa.String(), nullable=False),
    sa.Column('training_type', sa.String(), nullable=False),
    sa.Column('checkpoint_path', sa.String(), nullable=False),
    sa.Column('size_gb', sa.Float(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('parent_model_id', sa.String(), nullable=True),
    sa.Column('dataset_hash', sa.String(), nullable=False),
    sa.Column('eval_scores', sa.JSON(), nullable=False),
    sa.Column('children_count', sa.Integer(), nullable=False),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('base_model', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('current_loss', sa.Float(), nullable=True),
    sa.Column('loss_history', sa.JSON(), nullable=False),
    sa.Column('step_history', sa.JSON(), nullable=False),
    sa.Column('gpu_utilization', sa.JSON(), nullable=False),
    sa.Column('vram_used_gb', sa.Float(), nullable=False),
    sa.Column('vram_total_gb', sa.Float(), nullable=False),
    sa.Column('eval_scores', sa.JSON(), nullable=True),
    sa.Column('lineage_node_id', sa.String(), nullable=True),
    sa.Column('parent_model_id', sa.String(), nullable=True),
    sa.Column('dataset_hash', sa.String(), nullable=True),
    sa.Column('logs_tail', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_jobs')
    op.drop_table('model_checkpoints')
    op.drop_table('lineage_nodes')
    op.drop_table('lineage_edges')
    op.drop_table('datasets')
    op.drop_table('cluster_nodes')
    op.drop_table('automl_searches')
    op.drop_table('automl_runs')
    op.drop_table('agents')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
